In [1]:
import numpy as np

In [2]:
np.array([0,1,2,3])

array([0, 1, 2, 3])

In [4]:
np.eye(3 , dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
A = np.eye(2,2)
B = np.ones((2,2))
np.vstack((A,B))

array([[1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.hstack((A,B))

array([[1., 0., 1., 1.],
       [0., 1., 1., 1.]])

In [14]:
np.block([[A,B] , [B,A]])

array([[1., 0., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [18]:
np.loadtxt('numpy.csv' , skiprows=1 , delimiter=',')

array([[0., 1., 2.],
       [1., 0., 3.],
       [4., 5., 6.]])

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[-2:10]

array([8, 9])

In [39]:
arr2 = np.arange(1,36).reshape(5,7) 
arr2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

In [40]:
arr2[np.array([0,2,3]) , 1:3]

array([[ 2,  3],
       [16, 17],
       [23, 24]])

In [43]:
x = np.arange(0, 50, 10)
x[np.array([1,1,3,2])] += 1
x

array([ 0, 11, 21, 31, 40])

In [45]:
y = x[1:3]
y

array([11, 21])

In [46]:
print(y.base)

[ 0 11 21 31 40]


In [ ]:
x = np.arange(9).reshape(3,3)